version: 2
jobs:
  build:
    working_directory: ~/purge
    docker:
      - image: circleci/node:8.9.3-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: Install node_modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Bulding
          command: npm run build
      - save_cache:
          key: angular-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - public
  deploy:
    working_directory: ~/purge
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: angular-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install aws cli
          command: sudo pip install awsebcli
      - run:
          name: Upgrade botocore
          command: pip install --upgrade botocore
      - run:
          name: Setup AWS credentials
          command: |
            mkdir ~/.aws && printf "[profile eb-cli]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
      - deploy:
          name: Deploy to Elastic Beanstalk
          command: |
            eb deploy --debug
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
          - build
  
  